### ISSUE TITLE
Can we remove this method?

### ISSUE THREAD

**Issue by Luca-Ilari** [bendoz0/sendudes#29]
https://github.com/bendoz0/sendudes/blob/45e951bc5ce7dc87d08ba63faad1ad7fb0e1746e/app/src/main/java/it/startup/sendudes/ui/history/HistoryFragment.java#L54

**Comment by rohit20v** [comment]
yes 👍

**Comment by Luca-Ilari** [comment]
https://github.com/bendoz0/sendudes/compare/master...29-can-we-remove-this-method

**Comment by Nugg7** [comment]
y
